### ISSUE TITLE
change ringffer's item to "void *"

### ISSUE THREAD

**Issue by zhangxichao** [MaJerle/ringbuff#1]
Hi,MaJerle:
     I have a suggestion to change uint8_t* buff to void *buff，In this way, the ring buffer can be similar to a queue, and its item can be structured, two-dimensional arrays, and so on.

**Comment by MaJerle** [comment]
Very bad proposal. Purpose of buffer is to hold data. What you put inside with write function is up to you.

**Comment by zhangxichao** [comment]
In your GSM_AT_LIB_Res project, you use the FreeRTOS queue to send data to the producer thread. Without the support of the FreeRTOS queue, what should we do in the case of a single loop?

**Comment by MaJerle** [comment]
You do not understand purpose of this library.
Buffer by itself can hold bytes. Now what these bytes are is up to user who uses the buffer. How it is implemented in the lib is not necessary to know, until you have your data.

Function prototypes clearly accepts `void *` as it doesn't know what type of data it expects.
```c
size_t      ringbuff_write(ringbuff_t* buff, const void* data, size_t count);
size_t      ringbuff_read(ringbuff_t* buff, void* data, size_t count);
```

Now if you data is of type `void *`, you have to write bytes to save full `void *` memory

```c
void* ptr = (void *)0x123456;
ringbuff_write(&buff, ptr, sizeof(ptr));
```

And later, to read that `void *` value, you can do:

```c
void* ptr;
rindbuff_read(&buff, &ptr, sizeof(ptr));
```

You don't need to know what is happening internally in the library. Period.

**Comment by zhangxichao** [comment]
You're an element that represents a byte, but I want to implement something like a FreeRTOS queue, where each item of my data is a one-dimensional array.

For example, I want to send 10 messages, each of which is a one-dimensional array. With the help of this library, what should I do?

**Comment by MaJerle** [comment]
```c
typedef struct { int a; int b; int c; } my_struct; /* That's your element */
my_struct data[20]; /* 20 elements */

/* Write data */
ringbuff_write(&buff, data, sizeof(data));
```

This is not FreeRTOS but general buffer instead.

**Comment by zhangxichao** [comment]
> 
> 
> You do not understand purpose of this library.
> Buffer by itself can hold bytes. Now what these bytes are is up to user who uses the buffer. How it is implemented in the lib is not necessary to know, until you have your data.
> 
> Function prototypes clearly accepts `void *` as it doesn't know what type of data it expects.
> 
> ```c
> size_t      ringbuff_write(ringbuff_t* buff, const void* data, size_t count);
> size_t      ringbuff_read(ringbuff_t* buff, void* data, size_t count);
> ```
> 
> Now if you data is of type `void *`, you have to write bytes to save full `void *` memory
> 
> ```c
> float val = 13.4f;
> ringbuff_write(&buff, &val, sizeof(val));
> ```
> 
> And later, to read that `void *` value, you can do:
> 
> ```c
> float val;
> rindbuff_read(&buff, &val, sizeof(val));
> ```
> 
> You don't need to know what is happening internally in the library. Period.

I don't know which address the data from is the beginning of this floating point number.

**Comment by MaJerle** [comment]
Why do you need to know this?

**Comment by zhangxichao** [comment]
> Why do you need to know this?



If I don't know, how can I restore floating point numbers?

**Comment by MaJerle** [comment]
https://en.wikipedia.org/wiki/Circular_buffer please read.
Short. You store float value to the buffer and then on read, you read it back to your variable.

We will stop now at this point.

**Comment by zhangxichao** [comment]
In this case, the element can be changed to float * buff, which is more appropriate.

**Comment by zhangxichao** [comment]
Ringbuffer is to stream all bytes of all data structures

**Comment by MaJerle** [comment]
https://repl.it/@MaJerle/VibrantIncredibleWorker

**Comment by zhangxichao** [comment]
I'm sorry, but I'd like to ask you one more question.
Can't I use this idea to achieve a simple circular queue?
For example，

u8 mybuff[10][20];
struct buffer
{
   u8 (*pbuff)[20]; //pbuff = mybuff
   u8 w;
   u8 r;
   u8 size;  //The maximum size is 10.
}

In this way, read and write pointers are used to record the movement of pbuff line pointers.

**Comment by MaJerle** [comment]
What is the benefit over my solution?

**Comment by zhangxichao** [comment]
Similar to a circular queue. Isn't it?

**Comment by MaJerle** [comment]
You obviously have no clue :)
Circular queue is exactly the same as ring buffer. Did you even check my example?
